### PR TITLE
Add condstraint on batteries

### PR DESCRIPTION
**Pull request by Chris00**

### CODE REVIEW

**Comment by darioteixeira** [comment]
Alright. (I'm not yet using oasis2opam, though.)

**Comment by Chris00** [comment]
It is also useful for people trying to compile your project from a Git checkout as they will have an early warning if the version constraint is not satisfied.

**Comment by darioteixeira** [comment]
@Chris00: That's fair.  Though I've been putting the `opam` file at the root of all my projects to make life easier for those wanting to play with dev versions (`opam pin add ccss --dev-repo`, for instance).

**Comment by Chris00** [comment]
You do not have to do the job twice!  Add a constraint to `_oasis` and let (say using a make rule) `oasis2opam --local` update your local opam file .

**Pull request merged**
